when:
  - event: push
    branch: main

steps:
  - name: build
    image: node:22
    commands:
      - npm ci
      - npm run build
      - mv build public

  - name: publish
    image: bitnami/git
    secrets: [codeberg_token]
    commands:
      - git config --global user.email "pages@codeberg.org"
      - git config --global user.name "Codeberg Pages"
      - git clone --depth 1 https://codeberg.org/$CI_REPO/pages.git pages_repo || git clone https://codeberg.org/$CI_REPO/pages.git pages_repo
      - rm -rf pages_repo/*
      - cp -r public/* pages_repo/
      - cd pages_repo
      - git add -A
      - git commit -m "Deploy from commit $CI_COMMIT_SHA" || exit 0
      - git push https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO/pages.git HEAD:main
